version: "2"

services:
  app:
    command: ahgora-timekeeper
    build: .
    environment:
      ACCOUNT: "454"
      PASSWORD: "454"
      IDENTITY: "51eec6356c615d3edf39d497c137d75b"
      AHGORA_URL: "https://www.ahgora.com.br"
      LOG_LEVEL: "DEBUG"
      AHGORA_MOCK_SERVER_ENABLED: "false"
    ports: 
      - 5000:5000